version: "3.7"

services:
  app:
    build: .
    tty: true
    environment:
      - FLASK_ENV=$FLASK_ENV
      - SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_DATABASE_URI
      - SQLALCHEMY_TRACK_MODIFICATIONS=$SQLALCHEMY_TRACK_MODIFICATIONS
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./app:/app/
