version: "3.7"

services:
  app:
    build: .
    tty: true
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
      - FLASK_ENV=development
    ports:
      - 5000:5000
    volumes:
      - ./app:/app/